
services:
  web:
    build: .
    container_name: base_admin
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    volumes:
      - .:/app:cached          # project code
      - ./logs:/app/logs       # logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
